/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-gigab2b-categories.mjs — do not edit manually */
import type { Category } from '../types';

export type Gigab2bNode = {
  name: string;
  slug: string;
  children?: Gigab2bNode[];
};

/** GIGAB2B taxonomy: 18 level-1, 120 level-2, 212 level-3 */
export const GIGAB2B_TREE: Gigab2bNode[] = [
  {
    "name": "Furniture",
    "slug": "furniture",
    "children": [
      {
        "name": "Bedroom Furniture",
        "slug": "bedroom-furniture",
        "children": [
          {
            "name": "Beds, Frames & Bases",
            "slug": "beds-frames-bases"
          },
          {
            "name": "Bedroom Sets",
            "slug": "bedroom-sets"
          },
          {
            "name": "Makeup Vanities",
            "slug": "makeup-vanities"
          },
          {
            "name": "Vanity Stools & Chairs",
            "slug": "vanity-stools-chairs"
          },
          {
            "name": "Nightstands",
            "slug": "nightstands"
          },
          {
            "name": "Benches & Stools",
            "slug": "benches-stools"
          },
          {
            "name": "Jewelry Storage",
            "slug": "jewelry-storage"
          },
          {
            "name": "Bedroom Storage",
            "slug": "bedroom-storage"
          },
          {
            "name": "Dressers, Chests & Wardrobes",
            "slug": "dressers-chests-wardrobes"
          },
          {
            "name": "Mattresses",
            "slug": "mattresses"
          }
        ]
      },
      {
        "name": "Dining Furniture",
        "slug": "dining-furniture",
        "children": [
          {
            "name": "Dining and Kitchen Sets",
            "slug": "dining-and-kitchen-sets"
          },
          {
            "name": "Bar Tables",
            "slug": "bar-tables"
          },
          {
            "name": "Benches",
            "slug": "benches"
          },
          {
            "name": "Dining Tables",
            "slug": "dining-tables"
          },
          {
            "name": "Seating for Dining",
            "slug": "seating-for-dining"
          },
          {
            "name": "Servers, Sideboards & Buffets",
            "slug": "servers-sideboards-buffets"
          },
          {
            "name": "Kitchen Islands & Carts",
            "slug": "kitchen-islands-carts"
          }
        ]
      },
      {
        "name": "Primary Living Space",
        "slug": "primary-living-space",
        "children": [
          {
            "name": "Sectionals",
            "slug": "sectionals"
          },
          {
            "name": "Sofas",
            "slug": "sofas"
          },
          {
            "name": "Loveseats",
            "slug": "loveseats"
          },
          {
            "name": "Sofa Beds",
            "slug": "sofa-beds"
          },
          {
            "name": "Ottomans",
            "slug": "ottomans"
          },
          {
            "name": "Recliners & Massage Chairs",
            "slug": "recliners-massage-chairs"
          },
          {
            "name": "Chairs & Accent Seating",
            "slug": "chairs-accent-seating"
          },
          {
            "name": "Tables",
            "slug": "tables"
          },
          {
            "name": "Bean Bag Chairs & Lazy Sofa Chair",
            "slug": "bean-bag-chairs-lazy-sofa-chair"
          },
          {
            "name": "Rocking Chairs",
            "slug": "rocking-chairs"
          },
          {
            "name": "TV & Entertainment Furniture",
            "slug": "tv-entertainment-furniture"
          },
          {
            "name": "Storage Benches",
            "slug": "storage-benches"
          },
          {
            "name": "Indoor Fireplaces & Accessories",
            "slug": "indoor-fireplaces-accessories"
          },
          {
            "name": "Trash Cans",
            "slug": "trash-cans"
          },
          {
            "name": "Display, Shelving & Etageres",
            "slug": "display-shelving-etageres"
          },
          {
            "name": "Cabinets",
            "slug": "cabinets"
          },
          {
            "name": "Coat Racks",
            "slug": "coat-racks"
          },
          {
            "name": "Living Room Sets",
            "slug": "living-room-sets"
          }
        ]
      },
      {
        "name": "Office",
        "slug": "office",
        "children": [
          {
            "name": "Desks & Work Surfaces",
            "slug": "desks-work-surfaces"
          },
          {
            "name": "Office Chairs",
            "slug": "office-chairs"
          },
          {
            "name": "File Cabinets & Storage Cabinets",
            "slug": "file-cabinets-storage-cabinets"
          },
          {
            "name": "Safes",
            "slug": "safes"
          },
          {
            "name": "Desk Pads & Blotters",
            "slug": "desk-pads-blotters"
          },
          {
            "name": "Chair Mats",
            "slug": "chair-mats"
          }
        ]
      },
      {
        "name": "Game & Recreation",
        "slug": "game-recreation",
        "children": [
          {
            "name": "Seating & Chairs",
            "slug": "seating-chairs"
          },
          {
            "name": "Game Tables",
            "slug": "game-tables"
          },
          {
            "name": "Massage Tables",
            "slug": "massage-tables"
          }
        ]
      },
      {
        "name": "Youth, Kids & Baby Furniture",
        "slug": "youth-kids-baby-furniture",
        "children": [
          {
            "name": "Youth, Kids & Baby Furniture",
            "slug": "youth-kids-baby-furniture-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Garden & Outdoor",
    "slug": "garden-outdoor",
    "children": [
      {
        "name": "Outdoor & Patio Furniture",
        "slug": "outdoor-patio-furniture",
        "children": [
          {
            "name": "Patio Furniture Sets",
            "slug": "patio-furniture-sets"
          },
          {
            "name": "Patio Seating",
            "slug": "patio-seating"
          },
          {
            "name": "Outdoor Tables",
            "slug": "outdoor-tables"
          },
          {
            "name": "Fences",
            "slug": "fences"
          },
          {
            "name": "Deck Boxes & Patio Storage",
            "slug": "deck-boxes-patio-storage"
          }
        ]
      },
      {
        "name": "Canopies & Gazebos",
        "slug": "canopies-gazebos",
        "children": [
          {
            "name": "Umbrellas & Shades",
            "slug": "umbrellas-shades"
          },
          {
            "name": "Umbrella Stands & Bases",
            "slug": "umbrella-stands-bases"
          },
          {
            "name": "Carports",
            "slug": "carports"
          },
          {
            "name": "Pergolas",
            "slug": "pergolas"
          },
          {
            "name": "Gazebos",
            "slug": "gazebos"
          },
          {
            "name": "Canopies",
            "slug": "canopies"
          }
        ]
      },
      {
        "name": "Outdoor Heating",
        "slug": "outdoor-heating",
        "children": [
          {
            "name": "Outdoor Heating",
            "slug": "outdoor-heating-2"
          }
        ]
      },
      {
        "name": "Sheds",
        "slug": "sheds",
        "children": [
          {
            "name": "Sheds",
            "slug": "sheds-2"
          }
        ]
      },
      {
        "name": "Tents",
        "slug": "tents",
        "children": [
          {
            "name": "Tents",
            "slug": "tents-2"
          }
        ]
      },
      {
        "name": "Outdoor Decor",
        "slug": "outdoor-decor",
        "children": [
          {
            "name": "Outdoor Decor",
            "slug": "outdoor-decor-2"
          }
        ]
      },
      {
        "name": "Outdoor Cooking",
        "slug": "outdoor-cooking",
        "children": [
          {
            "name": "BBQ Grills & Outdoor Cooking Supplies",
            "slug": "bbq-grills-outdoor-cooking-supplies"
          },
          {
            "name": "Coolers",
            "slug": "coolers"
          }
        ]
      },
      {
        "name": "Garden Supplies",
        "slug": "garden-supplies",
        "children": [
          {
            "name": "Garden Carts",
            "slug": "garden-carts"
          },
          {
            "name": "Garden Pots & Planters",
            "slug": "garden-pots-planters"
          },
          {
            "name": "Garden Arch & Trellis",
            "slug": "garden-arch-trellis"
          },
          {
            "name": "Greenhouses",
            "slug": "greenhouses"
          },
          {
            "name": "Garden Bridges",
            "slug": "garden-bridges"
          }
        ]
      },
      {
        "name": "Pools",
        "slug": "pools",
        "children": [
          {
            "name": "Pools",
            "slug": "pools-2"
          }
        ]
      },
      {
        "name": "Power & Lawn Equipment",
        "slug": "power-lawn-equipment",
        "children": [
          {
            "name": "Weed Barrier Fabric",
            "slug": "weed-barrier-fabric"
          },
          {
            "name": "Lawn Aerator",
            "slug": "lawn-aerator"
          }
        ]
      },
      {
        "name": "Accessories",
        "slug": "accessories",
        "children": [
          {
            "name": "Accessories",
            "slug": "accessories-2"
          }
        ]
      },
      {
        "name": "Outdoor Generators & Portable Power",
        "slug": "outdoor-generators-portable-power",
        "children": [
          {
            "name": "Outdoor Generators & Portable Power",
            "slug": "outdoor-generators-portable-power-2"
          }
        ]
      },
      {
        "name": "Outdoor Hygiene & Sanitation",
        "slug": "outdoor-hygiene-sanitation",
        "children": [
          {
            "name": "Outdoor Hygiene & Sanitation",
            "slug": "outdoor-hygiene-sanitation-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Fitness & Sports",
    "slug": "fitness-sports",
    "children": [
      {
        "name": "Fitness",
        "slug": "fitness",
        "children": [
          {
            "name": "Elliptical Trainers",
            "slug": "elliptical-trainers"
          },
          {
            "name": "Exercise Bikes",
            "slug": "exercise-bikes"
          },
          {
            "name": "Inversion Equipment",
            "slug": "inversion-equipment"
          },
          {
            "name": "Rowers",
            "slug": "rowers"
          },
          {
            "name": "Step Machines",
            "slug": "step-machines"
          },
          {
            "name": "Trampolines",
            "slug": "trampolines"
          },
          {
            "name": "Treadmills",
            "slug": "treadmills"
          },
          {
            "name": "Vibration Platforms",
            "slug": "vibration-platforms"
          },
          {
            "name": "Fishing Kayaks",
            "slug": "fishing-kayaks"
          },
          {
            "name": "Weight Benches",
            "slug": "weight-benches"
          },
          {
            "name": "Water sports",
            "slug": "water-sports"
          },
          {
            "name": "Weight Racks",
            "slug": "weight-racks"
          },
          {
            "name": "Other Exercise Equipment",
            "slug": "other-exercise-equipment"
          }
        ]
      },
      {
        "name": "Sports",
        "slug": "sports",
        "children": [
          {
            "name": "Outdoor Bikes",
            "slug": "outdoor-bikes"
          },
          {
            "name": "Skateboards",
            "slug": "skateboards"
          },
          {
            "name": "Table Tennis Tables",
            "slug": "table-tennis-tables"
          },
          {
            "name": "Gym Mats",
            "slug": "gym-mats"
          },
          {
            "name": "Golf Bag Push Carts",
            "slug": "golf-bag-push-carts"
          },
          {
            "name": "Golf Sets",
            "slug": "golf-sets"
          },
          {
            "name": "Inflatable Paddle Boards",
            "slug": "inflatable-paddle-boards"
          },
          {
            "name": "Basketball Hoops",
            "slug": "basketball-hoops"
          },
          {
            "name": "Kick Scooters",
            "slug": "kick-scooters"
          },
          {
            "name": "Soccer Tables",
            "slug": "soccer-tables"
          },
          {
            "name": "Pool Tables",
            "slug": "pool-tables"
          },
          {
            "name": "Rod Racks",
            "slug": "rod-racks"
          }
        ]
      }
    ]
  },
  {
    "name": "Bath & Faucets",
    "slug": "bath-faucets",
    "children": [
      {
        "name": "Bathtubs",
        "slug": "bathtubs",
        "children": [
          {
            "name": "Bathtubs",
            "slug": "bathtubs-2"
          }
        ]
      },
      {
        "name": "Showers",
        "slug": "showers",
        "children": [
          {
            "name": "Shower Doors",
            "slug": "shower-doors"
          },
          {
            "name": "Shower Walls, Panels, & Surrounds",
            "slug": "shower-walls-panels-surrounds"
          },
          {
            "name": "Shower Bases & Pans",
            "slug": "shower-bases-pans"
          }
        ]
      },
      {
        "name": "Toilets & Bidets",
        "slug": "toilets-bidets",
        "children": [
          {
            "name": "Toilets & Bidets",
            "slug": "toilets-bidets-2"
          }
        ]
      },
      {
        "name": "Bathroom Sinks",
        "slug": "bathroom-sinks",
        "children": [
          {
            "name": "Bathroom Sinks",
            "slug": "bathroom-sinks-2"
          }
        ]
      },
      {
        "name": "Bathroom Vanities",
        "slug": "bathroom-vanities",
        "children": [
          {
            "name": "Bathroom Vanities",
            "slug": "bathroom-vanities-2"
          }
        ]
      },
      {
        "name": "Freestanding Tub Faucets",
        "slug": "freestanding-tub-faucets",
        "children": [
          {
            "name": "Freestanding Tub Faucets",
            "slug": "freestanding-tub-faucets-2"
          }
        ]
      },
      {
        "name": "Saunas",
        "slug": "saunas",
        "children": [
          {
            "name": "Saunas",
            "slug": "saunas-2"
          }
        ]
      },
      {
        "name": "Bathroom Sink Faucets",
        "slug": "bathroom-sink-faucets",
        "children": [
          {
            "name": "Bathroom Sink Faucets",
            "slug": "bathroom-sink-faucets-2"
          }
        ]
      },
      {
        "name": "Washer & Dryers",
        "slug": "washer-dryers",
        "children": [
          {
            "name": "Dryers",
            "slug": "dryers"
          }
        ]
      },
      {
        "name": "Bathroom Storage",
        "slug": "bathroom-storage",
        "children": [
          {
            "name": "Bathroom Storage",
            "slug": "bathroom-storage-2"
          }
        ]
      },
      {
        "name": "Bathroom Accessories",
        "slug": "bathroom-accessories",
        "children": [
          {
            "name": "Bathroom Accessories",
            "slug": "bathroom-accessories-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Kitchen",
    "slug": "kitchen",
    "children": [
      {
        "name": "Kitchen Sinks",
        "slug": "kitchen-sinks",
        "children": [
          {
            "name": "Kitchen Sinks",
            "slug": "kitchen-sinks-2"
          }
        ]
      },
      {
        "name": "Kitchen Faucets",
        "slug": "kitchen-faucets",
        "children": [
          {
            "name": "Kitchen Faucets",
            "slug": "kitchen-faucets-2"
          }
        ]
      },
      {
        "name": "Refrigerators",
        "slug": "refrigerators",
        "children": [
          {
            "name": "Refrigerators",
            "slug": "refrigerators-2"
          }
        ]
      },
      {
        "name": "Meat Grinders",
        "slug": "meat-grinders",
        "children": [
          {
            "name": "Meat Grinders",
            "slug": "meat-grinders-2"
          }
        ]
      },
      {
        "name": "Dish Drying Racks",
        "slug": "dish-drying-racks",
        "children": [
          {
            "name": "Dish Drying Racks",
            "slug": "dish-drying-racks-2"
          }
        ]
      },
      {
        "name": "Wine Cellars",
        "slug": "wine-cellars",
        "children": [
          {
            "name": "Wine Cellars",
            "slug": "wine-cellars-2"
          }
        ]
      },
      {
        "name": "Spice Racks",
        "slug": "spice-racks",
        "children": [
          {
            "name": "Spice Racks",
            "slug": "spice-racks-2"
          }
        ]
      },
      {
        "name": "Food Sanitizer",
        "slug": "food-sanitizer",
        "children": [
          {
            "name": "Food Sanitizer",
            "slug": "food-sanitizer-2"
          }
        ]
      },
      {
        "name": "Wine Racks",
        "slug": "wine-racks",
        "children": [
          {
            "name": "Wine Racks",
            "slug": "wine-racks-2"
          }
        ]
      },
      {
        "name": "Espresso Machines",
        "slug": "espresso-machines",
        "children": [
          {
            "name": "Espresso Machines",
            "slug": "espresso-machines-2"
          }
        ]
      },
      {
        "name": "Kitchen Appliances",
        "slug": "kitchen-appliances",
        "children": [
          {
            "name": "Cooktops",
            "slug": "cooktops"
          },
          {
            "name": "Toasters & Ovens",
            "slug": "toasters-ovens"
          },
          {
            "name": "Ice Cream Machines",
            "slug": "ice-cream-machines"
          },
          {
            "name": "Mixers",
            "slug": "mixers"
          },
          {
            "name": "Ice Makers",
            "slug": "ice-makers"
          },
          {
            "name": "Juicers",
            "slug": "juicers"
          },
          {
            "name": "Blenders",
            "slug": "blenders"
          }
        ]
      },
      {
        "name": "Accessories",
        "slug": "accessories-3",
        "children": [
          {
            "name": "Accessories",
            "slug": "accessories-4"
          }
        ]
      },
      {
        "name": "Baker's Racks",
        "slug": "bakers-racks",
        "children": [
          {
            "name": "Baker's Racks",
            "slug": "bakers-racks-2"
          }
        ]
      },
      {
        "name": "Ventilation",
        "slug": "ventilation",
        "children": [
          {
            "name": "Kitchen Range Hoods",
            "slug": "kitchen-range-hoods"
          }
        ]
      }
    ]
  },
  {
    "name": "Pet Supplies",
    "slug": "pet-supplies",
    "children": [
      {
        "name": "Pet Beds & Furniture",
        "slug": "pet-beds-furniture",
        "children": [
          {
            "name": "Pet Beds & Furniture",
            "slug": "pet-beds-furniture-2"
          }
        ]
      },
      {
        "name": "Grooming",
        "slug": "grooming",
        "children": [
          {
            "name": "Grooming",
            "slug": "grooming-2"
          }
        ]
      },
      {
        "name": "Pens & Hutches",
        "slug": "pens-hutches",
        "children": [
          {
            "name": "Pens & Hutches",
            "slug": "pens-hutches-2"
          }
        ]
      },
      {
        "name": "Trees & Condos",
        "slug": "trees-condos",
        "children": [
          {
            "name": "Trees & Condos",
            "slug": "trees-condos-2"
          }
        ]
      },
      {
        "name": "Pet Strollers",
        "slug": "pet-strollers",
        "children": [
          {
            "name": "Pet Strollers",
            "slug": "pet-strollers-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Toys",
    "slug": "toys",
    "children": [
      {
        "name": "Kids Bikes & Riding Toys",
        "slug": "kids-bikes-riding-toys",
        "children": [
          {
            "name": "Kids Bikes & Riding Toys",
            "slug": "kids-bikes-riding-toys-2"
          }
        ]
      },
      {
        "name": "Rockers",
        "slug": "rockers",
        "children": [
          {
            "name": "Rockers",
            "slug": "rockers-2"
          }
        ]
      },
      {
        "name": "Swing Sets",
        "slug": "swing-sets",
        "children": [
          {
            "name": "Swing Sets",
            "slug": "swing-sets-2"
          }
        ]
      },
      {
        "name": "Outdoor Sports",
        "slug": "outdoor-sports",
        "children": [
          {
            "name": "Outdoor Sports",
            "slug": "outdoor-sports-2"
          }
        ]
      },
      {
        "name": "Kids Kitchen Playsets",
        "slug": "kids-kitchen-playsets",
        "children": [
          {
            "name": "Kids Kitchen Playsets",
            "slug": "kids-kitchen-playsets-2"
          }
        ]
      },
      {
        "name": "Kids Slides",
        "slug": "kids-slides",
        "children": [
          {
            "name": "Kids Slides",
            "slug": "kids-slides-2"
          }
        ]
      },
      {
        "name": "Soft Play",
        "slug": "soft-play",
        "children": [
          {
            "name": "Soft Play",
            "slug": "soft-play-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Auto Parts & Transport",
    "slug": "auto-parts-transport",
    "children": [
      {
        "name": "Mobility Scooters",
        "slug": "mobility-scooters",
        "children": [
          {
            "name": "Mobility Scooters",
            "slug": "mobility-scooters-2"
          }
        ]
      },
      {
        "name": "Parts",
        "slug": "parts",
        "children": [
          {
            "name": "Parts",
            "slug": "parts-2"
          }
        ]
      },
      {
        "name": "Winches",
        "slug": "winches",
        "children": [
          {
            "name": "Winches",
            "slug": "winches-2"
          }
        ]
      },
      {
        "name": "Car Roof Tents",
        "slug": "car-roof-tents",
        "children": [
          {
            "name": "Car Roof Tents",
            "slug": "car-roof-tents-2"
          }
        ]
      },
      {
        "name": "Hand Trucks & Dollies",
        "slug": "hand-trucks-dollies",
        "children": [
          {
            "name": "Hand Trucks & Dollies",
            "slug": "hand-trucks-dollies-2"
          }
        ]
      },
      {
        "name": "Automotive Interior Coolers",
        "slug": "automotive-interior-coolers",
        "children": [
          {
            "name": "Automotive Interior Coolers",
            "slug": "automotive-interior-coolers-2"
          }
        ]
      },
      {
        "name": "Car Jacks",
        "slug": "car-jacks",
        "children": [
          {
            "name": "Car Jacks",
            "slug": "car-jacks-2"
          }
        ]
      },
      {
        "name": "Ramps",
        "slug": "ramps",
        "children": [
          {
            "name": "Ramps",
            "slug": "ramps-2"
          }
        ]
      },
      {
        "name": "Cargo Carriers",
        "slug": "cargo-carriers",
        "children": [
          {
            "name": "Cargo Carriers",
            "slug": "cargo-carriers-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Lighting",
    "slug": "lighting",
    "children": [
      {
        "name": "Dining Room Lighting",
        "slug": "dining-room-lighting",
        "children": [
          {
            "name": "Dining Room Lighting",
            "slug": "dining-room-lighting-2"
          }
        ]
      },
      {
        "name": "Living Room Lighting",
        "slug": "living-room-lighting",
        "children": [
          {
            "name": "Living Room Lighting",
            "slug": "living-room-lighting-2"
          }
        ]
      },
      {
        "name": "Bedroom Lighting",
        "slug": "bedroom-lighting",
        "children": [
          {
            "name": "Bedroom Lighting",
            "slug": "bedroom-lighting-2"
          }
        ]
      },
      {
        "name": "Bathroom Lighting",
        "slug": "bathroom-lighting",
        "children": [
          {
            "name": "Bathroom Lighting",
            "slug": "bathroom-lighting-2"
          }
        ]
      },
      {
        "name": "Outdoor Lighting",
        "slug": "outdoor-lighting",
        "children": [
          {
            "name": "Outdoor Lighting",
            "slug": "outdoor-lighting-2"
          }
        ]
      },
      {
        "name": "Lighting Accessories",
        "slug": "lighting-accessories",
        "children": [
          {
            "name": "Lighting Accessories",
            "slug": "lighting-accessories-2"
          }
        ]
      },
      {
        "name": "Lighting & Lamps",
        "slug": "lighting-lamps",
        "children": [
          {
            "name": "Lighting & Lamps",
            "slug": "lighting-lamps-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Household Supplies & Décor",
    "slug": "household-supplies-decor",
    "children": [
      {
        "name": "Dining Room Lighting",
        "slug": "dining-room-lighting-3",
        "children": [
          {
            "name": "Dining Room Lighting",
            "slug": "dining-room-lighting-4"
          }
        ]
      },
      {
        "name": "Living Room Lighting",
        "slug": "living-room-lighting-3",
        "children": [
          {
            "name": "Living Room Lighting",
            "slug": "living-room-lighting-4"
          }
        ]
      },
      {
        "name": "Bedroom Lighting",
        "slug": "bedroom-lighting-3",
        "children": [
          {
            "name": "Bedroom Lighting",
            "slug": "bedroom-lighting-4"
          }
        ]
      },
      {
        "name": "Bathroom Lighting",
        "slug": "bathroom-lighting-3",
        "children": [
          {
            "name": "Bathroom Lighting",
            "slug": "bathroom-lighting-4"
          }
        ]
      },
      {
        "name": "Outdoor Lighting",
        "slug": "outdoor-lighting-3",
        "children": [
          {
            "name": "Outdoor Lighting",
            "slug": "outdoor-lighting-4"
          }
        ]
      },
      {
        "name": "Lighting Accessories",
        "slug": "lighting-accessories-3",
        "children": [
          {
            "name": "Lighting Accessories",
            "slug": "lighting-accessories-4"
          }
        ]
      },
      {
        "name": "Lighting & Lamps",
        "slug": "lighting-lamps-3",
        "children": [
          {
            "name": "Lighting & Lamps",
            "slug": "lighting-lamps-4"
          }
        ]
      }
    ]
  },
  {
    "name": "Travel",
    "slug": "travel",
    "children": [
      {
        "name": "Luggage",
        "slug": "luggage",
        "children": [
          {
            "name": "Hard Case Luggage",
            "slug": "hard-case-luggage"
          },
          {
            "name": "Soft Case",
            "slug": "soft-case"
          }
        ]
      },
      {
        "name": "Backpacks",
        "slug": "backpacks",
        "children": [
          {
            "name": "Backpacks",
            "slug": "backpacks-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Electrical Appliances",
    "slug": "electrical-appliances",
    "children": [
      {
        "name": "Home Cleaning",
        "slug": "home-cleaning",
        "children": [
          {
            "name": "Home Cleaning",
            "slug": "home-cleaning-2"
          }
        ]
      },
      {
        "name": "Dryers",
        "slug": "dryers-2",
        "children": [
          {
            "name": "Dryers",
            "slug": "dryers-3"
          }
        ]
      },
      {
        "name": "Dehumidifiers",
        "slug": "dehumidifiers",
        "children": [
          {
            "name": "Dehumidifiers",
            "slug": "dehumidifiers-2"
          }
        ]
      },
      {
        "name": "Office Electronics",
        "slug": "office-electronics",
        "children": [
          {
            "name": "Office Electronics",
            "slug": "office-electronics-2"
          }
        ]
      },
      {
        "name": "Air Conditioners",
        "slug": "air-conditioners",
        "children": [
          {
            "name": "Air Conditioners",
            "slug": "air-conditioners-2"
          }
        ]
      },
      {
        "name": "Vacuums & Floor Cleaning Machines",
        "slug": "vacuums-floor-cleaning-machines",
        "children": [
          {
            "name": "Vacuums & Floor Cleaning Machines",
            "slug": "vacuums-floor-cleaning-machines-2"
          }
        ]
      },
      {
        "name": "Fans",
        "slug": "fans",
        "children": [
          {
            "name": "Fans",
            "slug": "fans-2"
          }
        ]
      },
      {
        "name": "Home Audio",
        "slug": "home-audio",
        "children": [
          {
            "name": "Sound System",
            "slug": "sound-system"
          }
        ]
      }
    ]
  },
  {
    "name": "Tools & Tool Organizers",
    "slug": "tools-tool-organizers",
    "children": [
      {
        "name": "Ladders",
        "slug": "ladders",
        "children": [
          {
            "name": "Ladders",
            "slug": "ladders-2"
          }
        ]
      },
      {
        "name": "Ventilation Fans",
        "slug": "ventilation-fans",
        "children": [
          {
            "name": "Ventilation Fans",
            "slug": "ventilation-fans-2"
          }
        ]
      },
      {
        "name": "Wire Fencing",
        "slug": "wire-fencing",
        "children": [
          {
            "name": "Wire Fencing",
            "slug": "wire-fencing-2"
          }
        ]
      },
      {
        "name": "Tool Boxes",
        "slug": "tool-boxes",
        "children": [
          {
            "name": "Tool Boxes",
            "slug": "tool-boxes-2"
          }
        ]
      },
      {
        "name": "Tool Cabinets",
        "slug": "tool-cabinets",
        "children": [
          {
            "name": "Tool Cabinets",
            "slug": "tool-cabinets-2"
          }
        ]
      },
      {
        "name": "Tool Carts",
        "slug": "tool-carts",
        "children": [
          {
            "name": "Tool Carts",
            "slug": "tool-carts-2"
          }
        ]
      },
      {
        "name": "Snow Removal Tools",
        "slug": "snow-removal-tools",
        "children": [
          {
            "name": "Snow Removal Tools",
            "slug": "snow-removal-tools-2"
          }
        ]
      },
      {
        "name": "Power & Pneumatic Tools",
        "slug": "power-pneumatic-tools",
        "children": [
          {
            "name": "Power & Pneumatic Tools",
            "slug": "power-pneumatic-tools-2"
          }
        ]
      },
      {
        "name": "Blowers",
        "slug": "blowers",
        "children": [
          {
            "name": "Blowers",
            "slug": "blowers-2"
          }
        ]
      },
      {
        "name": "Industrial & Heavy Equipment",
        "slug": "industrial-heavy-equipment",
        "children": [
          {
            "name": "Skid Steer Auger Drives & Bits",
            "slug": "skid-steer-auger-drives-bits"
          },
          {
            "name": "ATV & UTV Attachments",
            "slug": "atv-utv-attachments"
          },
          {
            "name": "Tractor Attachments",
            "slug": "tractor-attachments"
          }
        ]
      }
    ]
  },
  {
    "name": "Home Improvement",
    "slug": "home-improvement",
    "children": [
      {
        "name": "Doors & Door Hardware",
        "slug": "doors-door-hardware",
        "children": [
          {
            "name": "Doors & Door Hardware",
            "slug": "doors-door-hardware-2"
          }
        ]
      },
      {
        "name": "Wall Treatment & Supplies",
        "slug": "wall-treatment-supplies",
        "children": [
          {
            "name": "Wall Treatment & Supplies",
            "slug": "wall-treatment-supplies-2"
          }
        ]
      }
    ]
  },
  {
    "name": "Commercial",
    "slug": "commercial",
    "children": [
      {
        "name": "Beauty & Personal Care",
        "slug": "beauty-personal-care",
        "children": [
          {
            "name": "Beauty & Personal Care",
            "slug": "beauty-personal-care-2"
          }
        ]
      },
      {
        "name": "Heat Press Machines",
        "slug": "heat-press-machines",
        "children": [
          {
            "name": "Heat Press Machines",
            "slug": "heat-press-machines-2"
          }
        ]
      },
      {
        "name": "Display Freezers & Refrigerators",
        "slug": "display-freezers-refrigerators",
        "children": [
          {
            "name": "Display Freezers & Refrigerators",
            "slug": "display-freezers-refrigerators-2"
          }
        ]
      },
      {
        "name": "Air Compressors",
        "slug": "air-compressors",
        "children": [
          {
            "name": "Air Compressors",
            "slug": "air-compressors-2"
          }
        ]
      },
      {
        "name": "Vending Machine",
        "slug": "vending-machine",
        "children": [
          {
            "name": "Vending Machine",
            "slug": "vending-machine-2"
          }
        ]
      },
      {
        "name": "Restaurant Appliances & Equipment",
        "slug": "restaurant-appliances-equipment",
        "children": [
          {
            "name": "Deep Fryers",
            "slug": "deep-fryers"
          },
          {
            "name": "Commercial Broilers",
            "slug": "commercial-broilers"
          },
          {
            "name": "Food Warmers",
            "slug": "food-warmers"
          },
          {
            "name": "Commercial Ranges",
            "slug": "commercial-ranges"
          },
          {
            "name": "Commercial Charbroilers",
            "slug": "commercial-charbroilers"
          }
        ]
      }
    ]
  },
  {
    "name": "Industrial & Scientific",
    "slug": "industrial-scientific",
    "children": [
      {
        "name": "Healthcare Furniture",
        "slug": "healthcare-furniture",
        "children": [
          {
            "name": "Patient Beds",
            "slug": "patient-beds"
          }
        ]
      }
    ]
  },
  {
    "name": "Other",
    "slug": "other",
    "children": [
      {
        "name": "Other",
        "slug": "other-2",
        "children": [
          {
            "name": "Other",
            "slug": "other-3"
          }
        ]
      }
    ]
  },
  {
    "name": "Part",
    "slug": "part",
    "children": [
      {
        "name": "Mobility Scooters",
        "slug": "mobility-scooters-3",
        "children": [
          {
            "name": "Mobility Scooters",
            "slug": "mobility-scooters-4"
          }
        ]
      },
      {
        "name": "Parts",
        "slug": "parts-3",
        "children": [
          {
            "name": "Parts",
            "slug": "parts-4"
          }
        ]
      },
      {
        "name": "Winches",
        "slug": "winches-3",
        "children": [
          {
            "name": "Winches",
            "slug": "winches-4"
          }
        ]
      },
      {
        "name": "Car Roof Tents",
        "slug": "car-roof-tents-3",
        "children": [
          {
            "name": "Car Roof Tents",
            "slug": "car-roof-tents-4"
          }
        ]
      },
      {
        "name": "Hand Trucks & Dollies",
        "slug": "hand-trucks-dollies-3",
        "children": [
          {
            "name": "Hand Trucks & Dollies",
            "slug": "hand-trucks-dollies-4"
          }
        ]
      },
      {
        "name": "Automotive Interior Coolers",
        "slug": "automotive-interior-coolers-3",
        "children": [
          {
            "name": "Automotive Interior Coolers",
            "slug": "automotive-interior-coolers-4"
          }
        ]
      },
      {
        "name": "Car Jacks",
        "slug": "car-jacks-3",
        "children": [
          {
            "name": "Car Jacks",
            "slug": "car-jacks-4"
          }
        ]
      },
      {
        "name": "Ramps",
        "slug": "ramps-3",
        "children": [
          {
            "name": "Ramps",
            "slug": "ramps-4"
          }
        ]
      },
      {
        "name": "Cargo Carriers",
        "slug": "cargo-carriers-3",
        "children": [
          {
            "name": "Cargo Carriers",
            "slug": "cargo-carriers-4"
          }
        ]
      }
    ]
  }
];

export const GIGAB2B_LEVEL1_IMAGES: Record<string, string> = {
  "furniture": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=2000",
  "garden-outdoor": "https://images.unsplash.com/photo-1517409197771-1520a09e8b91?auto=format&fit=crop&q=80&w=2000",
  "fitness-sports": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=2000",
  "bath-faucets": "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&q=80&w=2000",
  "kitchen": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&q=80&w=2000",
  "pet-supplies": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&q=80&w=2000",
  "toys": "https://images.unsplash.com/photo-1515488042361-ee00e3ddd4d4?auto=format&fit=crop&q=80&w=2000",
  "auto-parts-transport": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=2000",
  "lighting": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=2000",
  "household-supplies-decor": "https://images.unsplash.com/photo-1513519247388-4e284044efd3?auto=format&fit=crop&q=80&w=2000",
  "travel": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80&w=2000",
  "electrical-appliances": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=2000",
  "tools-tool-organizers": "https://images.unsplash.com/photo-1581147036323-c1c5c7d2e672?auto=format&fit=crop&q=80&w=2000",
  "home-improvement": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=2000",
  "commercial": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=2000",
  "industrial-scientific": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=2000",
  "other": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&q=80&w=2000",
  "part": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=2000"
};

export const GIGAB2B_HERO_IMAGES: Record<string, string> = {
  "furniture": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=2000",
  "garden-outdoor": "https://images.unsplash.com/photo-1517409197771-1520a09e8b91?auto=format&fit=crop&q=80&w=2000",
  "fitness-sports": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=2000",
  "bath-faucets": "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&q=80&w=2000",
  "kitchen": "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&q=80&w=2000",
  "pet-supplies": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&q=80&w=2000",
  "toys": "https://images.unsplash.com/photo-1515488042361-ee00e3ddd4d4?auto=format&fit=crop&q=80&w=2000",
  "auto-parts-transport": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=2000",
  "lighting": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=2000",
  "household-supplies-decor": "https://images.unsplash.com/photo-1513519247388-4e284044efd3?auto=format&fit=crop&q=80&w=2000",
  "travel": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80&w=2000",
  "electrical-appliances": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=2000",
  "tools-tool-organizers": "https://images.unsplash.com/photo-1581147036323-c1c5c7d2e672?auto=format&fit=crop&q=80&w=2000",
  "home-improvement": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=2000",
  "commercial": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=2000",
  "industrial-scientific": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=2000",
  "other": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&q=80&w=2000",
  "part": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&q=80&w=2000"
};

export const GIGAB2B_HERO_SUBTITLES: Record<string, string> = {
  "furniture": "Bedroom, dining, living, office and more — curated for modern homes.",
  "garden-outdoor": "Patio sets, gazebos, grilling and everything for outdoor living.",
  "fitness-sports": "Home gyms, cardio equipment and sports gear.",
  "bath-faucets": "Bathtubs, vanities, showers and bathroom essentials.",
  "kitchen": "Appliances, sinks, storage and tools for the heart of your home.",
  "pet-supplies": "Comfortable beds, condos and care for your companions.",
  "toys": "Playsets, rides and outdoor fun for kids.",
  "auto-parts-transport": "Mobility, cargo and transport solutions.",
  "lighting": "Layered light for every room and outdoor space.",
  "household-supplies-decor": "Finishing touches and everyday home essentials.",
  "travel": "Luggage and backpacks built for the journey.",
  "electrical-appliances": "Climate, cleaning and home electronics.",
  "tools-tool-organizers": "Workshop tools, storage and outdoor power equipment.",
  "home-improvement": "Doors, hardware and wall treatments.",
  "commercial": "Professional equipment for business and hospitality.",
  "industrial-scientific": "Specialized furniture and equipment.",
  "other": "Discover more across our catalog.",
  "part": "Replacement parts and accessories."
};

/** Old 8-category slugs → new product category slug */
export const LEGACY_PRODUCT_CATEGORY_MAP: Record<string, string> = {
  "sofas": "sofas",
  "beds": "beds-frames-bases",
  "tables": "tables",
  "chairs": "chairs-and-accent-seating",
  "garden": "garden-outdoor",
  "lighting": "lighting",
  "storage": "display-shelving-etageres",
  "decor": "household-supplies-decor"
};

export const LEGACY_ROOT_CATEGORY_SLUGS = new Set([
  'sofas', 'beds', 'tables', 'chairs', 'garden', 'lighting', 'storage', 'decor',
]);

export const GIGAB2B_PRIMARY_NAV_SLUGS: string[] = ["furniture","garden-outdoor","fitness-sports","bath-faucets","kitchen","pet-supplies","toys","auto-parts-transport","lighting","household-supplies-decor","travel","electrical-appliances","tools-tool-organizers","home-improvement","commercial","industrial-scientific","other","part"];

function flattenTree(): Category[] {
  const out: Category[] = [];
  let sort = 0;
  const walk = (nodes: Gigab2bNode[], parentId: string | null) => {
    for (const node of nodes) {
      const id = `cat_gb_${node.slug}`;
      out.push({
        id,
        name: node.name,
        slug: node.slug,
        image: parentId ? '' : (GIGAB2B_LEVEL1_IMAGES[node.slug] || ''),
        parentId,
        sortOrder: sort++,
      });
      if (node.children?.length) walk(node.children, id);
    }
  };
  walk(GIGAB2B_TREE, null);
  return out;
}

let _flat: Category[] | null = null;

export function getGigab2bCategoriesFlat(): Category[] {
  if (!_flat) _flat = flattenTree();
  return _flat.map((c) => ({ ...c }));
}

export function buildGigab2bSlugLabelMap(): Record<string, string> {
  const map: Record<string, string> = { sale: 'Sale', accessories: 'Accessories' };
  for (const c of getGigab2bCategoriesFlat()) {
    map[c.slug] = c.name;
  }
  return map;
}

export function buildNavSublinksFromTree(): Record<string, { name: string; href: string }[]> {
  const flat = getGigab2bCategoriesFlat();
  const byParent = new Map<string | null, Category[]>();
  for (const c of flat) {
    const pid = c.parentId ?? null;
    if (!byParent.has(pid)) byParent.set(pid, []);
    byParent.get(pid)!.push(c);
  }
  for (const arr of byParent.values()) {
    arr.sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0));
  }
  const out: Record<string, { name: string; href: string }[]> = {};
  for (const l1 of byParent.get(null) || []) {
    const l2s = byParent.get(l1.id) || [];
    out[l1.slug] = l2s.slice(0, 8).map((c) => ({
      name: c.name,
      href: `/category/${c.slug}`,
    }));
  }
  return out;
}

export function isLegacyFlatCategoryTree(categories: Category[]): boolean {
  if (!categories.length) return false;
  const roots = categories.filter((c) => !c.parentId);
  if (roots.length > 12) return false;
  return roots.every((r) => LEGACY_ROOT_CATEGORY_SLUGS.has(r.slug));
}

export function migrateLegacyProductCategory(slug: string): string {
  const key = slug.trim().toLowerCase();
  return LEGACY_PRODUCT_CATEGORY_MAP[key] || key;
}

export const GIGAB2B_LEAF_SLUGS: string[] = [
  "beds-frames-bases",
  "bedroom-sets",
  "makeup-vanities",
  "vanity-stools-chairs",
  "nightstands",
  "benches-stools",
  "jewelry-storage",
  "bedroom-storage",
  "dressers-chests-wardrobes",
  "mattresses",
  "dining-and-kitchen-sets",
  "bar-tables",
  "benches",
  "dining-tables",
  "seating-for-dining",
  "servers-sideboards-buffets",
  "kitchen-islands-carts",
  "sectionals",
  "sofas",
  "loveseats",
  "sofa-beds",
  "ottomans",
  "recliners-massage-chairs",
  "chairs-accent-seating",
  "tables",
  "bean-bag-chairs-lazy-sofa-chair",
  "rocking-chairs",
  "tv-entertainment-furniture",
  "storage-benches",
  "indoor-fireplaces-accessories",
  "trash-cans",
  "display-shelving-etageres",
  "cabinets",
  "coat-racks",
  "living-room-sets",
  "desks-work-surfaces",
  "office-chairs",
  "file-cabinets-storage-cabinets",
  "safes",
  "desk-pads-blotters",
  "chair-mats",
  "seating-chairs",
  "game-tables",
  "massage-tables",
  "youth-kids-baby-furniture-2",
  "patio-furniture-sets",
  "patio-seating",
  "outdoor-tables",
  "fences",
  "deck-boxes-patio-storage",
  "umbrellas-shades",
  "umbrella-stands-bases",
  "carports",
  "pergolas",
  "gazebos",
  "canopies",
  "outdoor-heating-2",
  "sheds-2",
  "tents-2",
  "outdoor-decor-2",
  "bbq-grills-outdoor-cooking-supplies",
  "coolers",
  "garden-carts",
  "garden-pots-planters",
  "garden-arch-trellis",
  "greenhouses",
  "garden-bridges",
  "pools-2",
  "weed-barrier-fabric",
  "lawn-aerator",
  "accessories-2",
  "outdoor-generators-portable-power-2",
  "outdoor-hygiene-sanitation-2",
  "elliptical-trainers",
  "exercise-bikes",
  "inversion-equipment",
  "rowers",
  "step-machines",
  "trampolines",
  "treadmills",
  "vibration-platforms",
  "fishing-kayaks",
  "weight-benches",
  "water-sports",
  "weight-racks",
  "other-exercise-equipment",
  "outdoor-bikes",
  "skateboards",
  "table-tennis-tables",
  "gym-mats",
  "golf-bag-push-carts",
  "golf-sets",
  "inflatable-paddle-boards",
  "basketball-hoops",
  "kick-scooters",
  "soccer-tables",
  "pool-tables",
  "rod-racks",
  "bathtubs-2",
  "shower-doors",
  "shower-walls-panels-surrounds",
  "shower-bases-pans",
  "toilets-bidets-2",
  "bathroom-sinks-2",
  "bathroom-vanities-2",
  "freestanding-tub-faucets-2",
  "saunas-2",
  "bathroom-sink-faucets-2",
  "dryers",
  "bathroom-storage-2",
  "bathroom-accessories-2",
  "kitchen-sinks-2",
  "kitchen-faucets-2",
  "refrigerators-2",
  "meat-grinders-2",
  "dish-drying-racks-2",
  "wine-cellars-2",
  "spice-racks-2",
  "food-sanitizer-2",
  "wine-racks-2",
  "espresso-machines-2",
  "cooktops",
  "toasters-ovens",
  "ice-cream-machines",
  "mixers",
  "ice-makers",
  "juicers",
  "blenders",
  "accessories-4",
  "bakers-racks-2",
  "kitchen-range-hoods",
  "pet-beds-furniture-2",
  "grooming-2",
  "pens-hutches-2",
  "trees-condos-2",
  "pet-strollers-2",
  "kids-bikes-riding-toys-2",
  "rockers-2",
  "swing-sets-2",
  "outdoor-sports-2",
  "kids-kitchen-playsets-2",
  "kids-slides-2",
  "soft-play-2",
  "mobility-scooters-2",
  "parts-2",
  "winches-2",
  "car-roof-tents-2",
  "hand-trucks-dollies-2",
  "automotive-interior-coolers-2",
  "car-jacks-2",
  "ramps-2",
  "cargo-carriers-2",
  "dining-room-lighting-2",
  "living-room-lighting-2",
  "bedroom-lighting-2",
  "bathroom-lighting-2",
  "outdoor-lighting-2",
  "lighting-accessories-2",
  "lighting-lamps-2",
  "dining-room-lighting-4",
  "living-room-lighting-4",
  "bedroom-lighting-4",
  "bathroom-lighting-4",
  "outdoor-lighting-4",
  "lighting-accessories-4",
  "lighting-lamps-4",
  "hard-case-luggage",
  "soft-case",
  "backpacks-2",
  "home-cleaning-2",
  "dryers-3",
  "dehumidifiers-2",
  "office-electronics-2",
  "air-conditioners-2",
  "vacuums-floor-cleaning-machines-2",
  "fans-2",
  "sound-system",
  "ladders-2",
  "ventilation-fans-2",
  "wire-fencing-2",
  "tool-boxes-2",
  "tool-cabinets-2",
  "tool-carts-2",
  "snow-removal-tools-2",
  "power-pneumatic-tools-2",
  "blowers-2",
  "skid-steer-auger-drives-bits",
  "atv-utv-attachments",
  "tractor-attachments",
  "doors-door-hardware-2",
  "wall-treatment-supplies-2",
  "beauty-personal-care-2",
  "heat-press-machines-2",
  "display-freezers-refrigerators-2",
  "air-compressors-2",
  "vending-machine-2",
  "deep-fryers",
  "commercial-broilers",
  "food-warmers",
  "commercial-ranges",
  "commercial-charbroilers",
  "patient-beds",
  "other-3",
  "mobility-scooters-4",
  "parts-4",
  "winches-4",
  "car-roof-tents-4",
  "hand-trucks-dollies-4",
  "automotive-interior-coolers-4",
  "car-jacks-4",
  "ramps-4",
  "cargo-carriers-4"
];
